---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```


```{r}
library(tidyverse)
library(psych)
library(data.table)
library(GPArotation)
library(lavaan)
library(parameters)
library(nFactors)
library(see)
library(performance)
```

# Loading Data
```{r}
data = load("Latent_data.RData") 

set.seed(123)
a = sample(table, 30) 

a[] <- sapply(a, as.numeric) 

a = a %>%
  na.omit()

# check_factorstructure(a)
```


```{r}
b <- fa.parallel(a, cor = "poly", fa = "pc")
b$pc.values
b$pc.sim

res = fa(a, 5, cor = 'poly', rotate = 'geominQ', fm = 'wls')
res


res2 = fa(a, 6, cor = 'poly', rotate = 'geominQ', fm = 'wls')
res2
```



```{r}
efa <- psych::fa(a, nfactors = 5) %>%
  model_parameters(sort = TRUE, threshold = "max")

efa

efa6 <- psych::fa(a, nfactors = 6) %>%
  model_parameters(sort = TRUE, threshold = "max")

efa6
```


# Their code
```{r}
head(predict(efa, names = c("Neuroticism", "Conscientiousness", "Extraversion", "Agreeableness", "Opennness")), 5)
```


```{r}
n <- n_factors(a)
n

plot(n) + theme_modern()
```



```{r}
index <- datawizard::data_partition(a, training_proportion = 0.7, seed = 111)
train.data <- index$training
test.data <- index$test
```


```{r}
structure_big5 <- psych::fa(a, nfactors = 5) %>%
  efa_to_cfa()

structure_big3 <- psych::fa(a, nfactors = 6) %>%
  efa_to_cfa()

structure_big5
structure_big3
```


```{r}
big5 <- lavaan::cfa(structure_big5, data = test.data)
big3 <- lavaan::cfa(structure_big4, data = test.data)

performance::compare_performance(big5, big4)
```

# Our code
```{r}
model_big5 <-
  'MR1 =~ V315 + H1244 + H434 + H441 + V175 + N14
   MR2 =~ X68 + H1048 + H658 + H477 + H336 + E123 + V119 + Q146
   MR3 =~ X236 + H837 + H612 + Q251 + P492 + E146
   MR4 =~ C3 + H86 + Q104 + R26 + H698
   MR5 =~ Q68 + M29 + D107 + H1085 + Q29'

#run model
fit_std5 = cfa(model_big5, data = a, ordered = names(a), std.lv = TRUE)

#inspect model output
summary(fit_std5, rsquare = TRUE, fit.measures = TRUE)
```


# Our code
```{r}
model_big6 <-
  'MR3 =~ H837 + H477 + H612 + Q251 + P492 + E146
   MR1 =~ V315 + C3 + Q104 + V119 + V175 + N14
   MR5 =~ Q68 + H434 + M29 + D107 + H1085 + H698 + Q29
   MR4 =~ H1048 + H86 + R26
   MR2 =~ X68 + H658 + H336 + Q146
   MR6 =~ X236 + H1244 + E123 + H441'

#run model
fit_std6 = cfa(model_big6, data = a, ordered = names(a), std.lv = TRUE)

#inspect model output
summary(fit_std6, rsquare = TRUE, fit.measures = TRUE)
```



