---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```


```{r}
library(tidyverse)
library(psych)
library(data.table)
library(GPArotation)
library(lavaan)
library(parameters)
library(nFactors)
library(see)
library(performance)
```

- 2 diff samples
- compare cfi and rmsea

# Loading Data
```{r}
data = load("Latent_data.RData") 


a = table %>%
  dplyr::select(starts_with("H")) 

set.seed(123)
sample1 = sample(a, 30) 

sample1[] <- sapply(sample1, as.numeric) 

sample1 = sample1 %>%
  na.omit()

set.seed(333)
sample2 = sample(a, 30) 

sample2[] <- sapply(sample2, as.numeric) 

sample2 = sample2 %>%
  na.omit()

check_factorstructure(sample1)
check_factorstructure(sample2)
```



```{r}
b1 <- fa.parallel(sample1, cor = "poly", fa = "pc")
b1$pc.values
b1$pc.sim

# the number of components =  5 

b2 <- fa.parallel(sample2, cor = "poly", fa = "pc")
b2$pc.values
b2$pc.sim

# the number of components =  5 

res = fa(a, 5, cor = 'poly', rotate = 'geominQ', fm = 'wls')
res


res2 = fa(a, 6, cor = 'poly', rotate = 'geominQ', fm = 'wls')
res2
```



```{r}
efa1 <- psych::fa(sample1, nfactors = 5) %>%
  model_parameters(sort = TRUE, threshold = "max")

efa1

# RMSEA:  0.033

efa2 <- psych::fa(sample2, nfactors = 5) %>%
  model_parameters(sort = TRUE, threshold = "max")

# RMSEA: 0.026

summary(efa1, rsquare = TRUE, fit.measures = TRUE)
```


```{r}
structure_big1 <- psych::fa(sample1, nfactors = 5) %>%
  efa_to_cfa()

structure_big2 <- psych::fa(sample2, nfactors = 5) %>%
  efa_to_cfa()

structure_big1
structure_big2
```


# Our code
```{r}
model_big5 <-
  'MR1 =~ V315 + H1244 + H434 + H441 + V175 + N14
   MR2 =~ X68 + H1048 + H658 + H477 + H336 + E123 + V119 + Q146
   MR3 =~ X236 + H837 + H612 + Q251 + P492 + E146
   MR4 =~ C3 + H86 + Q104 + R26 + H698
   MR5 =~ Q68 + M29 + D107 + H1085 + Q29'

#run model
fit_std5 = cfa(model_big5, data = a, ordered = names(a), std.lv = TRUE)

#inspect model output
summary(fit_std5, rsquare = TRUE, fit.measures = TRUE)
```


# Our code
```{r}
model_big6 <-
  'MR3 =~ H837 + H477 + H612 + Q251 + P492 + E146
   MR1 =~ V315 + C3 + Q104 + V119 + V175 + N14
   MR5 =~ Q68 + H434 + M29 + D107 + H1085 + H698 + Q29
   MR4 =~ H1048 + H86 + R26
   MR2 =~ X68 + H658 + H336 + Q146
   MR6 =~ X236 + H1244 + E123 + H441'

#run model
fit_std6 = cfa(model_big6, data = a, ordered = names(a), std.lv = TRUE)

#inspect model output
summary(fit_std6, rsquare = TRUE, fit.measures = TRUE)
```



